const SHA = "7f3b2c8e6b3a1a9d3f5c4d9e7a2b6c1d8e9f0a1b2c3d4e5f67890abcde123456";

const modalityMeta = {
  FTIR: { label: "FTIR", format: "CSV" },
  TENSILE: { label: "拉伸", format: "XLSX" },
  RHEOLOGY: { label: "流变", format: "CSV" },
  SEM: { label: "SEM", format: "TIF" },
  GPC: { label: "GPC", format: "CSV" },
  TORQUE: { label: "扭矩", format: "CSV" },
  IMPACT: { label: "冲击", format: "RAW" },
  OPTICAL: { label: "光学图像", format: "TIF" },
  SIMULATION: { label: "模拟", format: "OUT" },
};

function genericFiles(name, modality, count) {
  const stem = name.replace(/-[A-Z]+-\d+$/, "");
  const meta = modalityMeta[modality] || modalityMeta.FTIR;
  const suffix = meta.format.toLowerCase();
  return Array.from({ length: count }, (_, index) => ({
    id: name + "-asset-" + (index + 1),
    name: stem + "_" + String(index + 1).padStart(2, "0") + "." + suffix,
    size: index === 0 ? "2.45 MB" : (860 - index * 37) + " KB",
    role: index === 0 ? "主测量文件" : "关联文件",
  }));
}

function makeDataset(input) {
  const meta = modalityMeta[input.modality] || modalityMeta.FTIR;
  const files = input.files || genericFiles(input.name, input.modality, input.fileCount);
  return {
    id: input.id || input.name,
    name: input.name,
    canonicalName: input.canonicalName || input.name,
    project: input.project,
    workstream: input.workstream || "PA_ADR_RECYCLE",
    sample: input.sample,
    modality: input.modality,
    modalityLabel: meta.label,
    materialState: input.materialState || "干燥态",
    materialStateCode: input.materialStateCode || "VIRGIN",
    fileCount: input.fileCount,
    confidence: input.confidence,
    status: input.status,
    statusCode: input.statusCode,
    updatedAt: input.updatedAt,
    date: input.date || input.updatedAt.slice(0, 10),
    format: input.format || meta.format,
    originalPath:
      input.originalPath ||
      "D:\\Data\\Inbox\\" + input.project.replaceAll(" ", "_") + "\\" + input.name,
    sha256: input.sha256 || SHA,
    hashVerified: input.hashVerified !== false,
    evidence:
      input.evidence || [
        "文件名包含测试关键词：" + meta.label,
        "文件扩展名与 " + meta.label + " 规则一致",
        "同目录文件具有相同采集时间窗口",
      ],
    files,
  };
}

export const seedDatasets = [
  makeDataset({
    name: "POM-20240515-FTIR-001",
    project: "POM 改性研究",
    sample: "POM-GF30-1",
    modality: "FTIR",
    fileCount: 3,
    confidence: 0.92,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-15 14:32",
  }),
  makeDataset({
    name: "PBT-20240515-TENS-002",
    project: "PBT 增韧项目",
    sample: "PBT-TA-2",
    modality: "TENSILE",
    fileCount: 5,
    confidence: 0.89,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-15 13:48",
  }),
  makeDataset({
    name: "NR-20240515-RHEO-003",
    project: "NR 配方优化",
    sample: "NR-50-3",
    modality: "RHEOLOGY",
    fileCount: 4,
    confidence: 0.91,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-15 11:21",
  }),
  makeDataset({
    name: "POM-20240514-SEM-004",
    project: "POM 改性研究",
    sample: "POM-GF30-1",
    modality: "SEM",
    fileCount: 12,
    confidence: 0.95,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-14 16:05",
  }),
  makeDataset({
    name: "PA66-20240514-GPC-005",
    project: "PA66 水解研究",
    sample: "PA66-H-1",
    modality: "GPC",
    fileCount: 6,
    confidence: 0.88,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-14 09:17",
  }),
  makeDataset({
    name: "PP-20240514-TORQUE-006",
    project: "PP 挤出工艺",
    sample: "PP-MI2-1",
    modality: "TORQUE",
    fileCount: 3,
    confidence: 0.9,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-14 08:42",
  }),
  makeDataset({
    name: "PBT-20240513-IMPACT-007",
    project: "PBT 增韧项目",
    sample: "PBT-TA-3",
    modality: "IMPACT",
    fileCount: 4,
    confidence: 0.63,
    status: "待审核",
    statusCode: "review",
    updatedAt: "2024-05-13 17:33",
    originalPath: "D:\\Data\\Inbox\\PBT\\Impact\\20240513",
    evidence: [
      "文件名包含关键词：Impact",
      "元数据字段：TestType = Impact",
      "数据文件头特征匹配 Izod/Charpy 冲击测试",
      "图像分辨率 1024×768，典型冲击断口图",
    ],
    files: [
      { id: "impact-1", name: "Impact_001.raw", size: "2.45 MB", role: "主测量文件" },
      { id: "impact-2", name: "Impact_001.meta", size: "1.21 KB", role: "元数据" },
      { id: "impact-3", name: "Impact_001.jpg", size: "854.21 KB", role: "断口图像" },
      { id: "impact-4", name: "Impact_001.txt", size: "2.02 KB", role: "文本导出" },
    ],
  }),
  makeDataset({
    name: "PC-20240513-OPTICAL-008",
    project: "PC 透明化研究",
    sample: "PC-UV-1",
    modality: "OPTICAL",
    fileCount: 8,
    confidence: 0.71,
    status: "待审核",
    statusCode: "review",
    updatedAt: "2024-05-13 15:11",
  }),
  makeDataset({
    name: "PPO-20240512-FTIR-009",
    project: "PPO 相容性研究",
    sample: "PPO-MAH-1",
    modality: "FTIR",
    fileCount: 3,
    confidence: 0.96,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-12 10:22",
  }),
  makeDataset({
    name: "PEEK-20240512-TENS-010",
    project: "PEEK 性能评估",
    sample: "PEEK-CF30",
    modality: "TENSILE",
    fileCount: 5,
    confidence: 0.94,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-12 09:03",
  }),
  makeDataset({
    name: "EPDM-20240511-RHEO-011",
    project: "EPDM 硫化优化",
    sample: "EPDM-BLEND",
    modality: "RHEOLOGY",
    fileCount: 4,
    confidence: 0.87,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-11 18:55",
  }),
  makeDataset({
    name: "ABS-20240511-SEM-012",
    project: "ABS 冲击改性",
    sample: "ABS-TiO2",
    modality: "SEM",
    fileCount: 10,
    confidence: 0.93,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-11 14:39",
  }),
  makeDataset({
    name: "PLA-20240510-GPC-013",
    project: "PLA 降解研究",
    sample: "PLA-2000",
    modality: "GPC",
    fileCount: 6,
    confidence: 0.75,
    status: "待审核",
    statusCode: "review",
    updatedAt: "2024-05-10 11:25",
  }),
  makeDataset({
    name: "PVC-20240510-TORQUE-014",
    project: "PVC 加工助剂",
    sample: "PVC-DOP",
    modality: "TORQUE",
    fileCount: 3,
    confidence: 0.96,
    status: "已入库",
    statusCode: "ingested",
    updatedAt: "2024-05-10 09:12",
  }),
  makeDataset({
    name: "PA66-20240509-SEM-015",
    project: "PA66 回收料",
    sample: "R-PA66-4",
    modality: "SEM",
    fileCount: 9,
    confidence: 0.41,
    status: "待审核",
    statusCode: "review",
    materialState: "回收料",
    materialStateCode: "RECYCLED",
    updatedAt: "2024-05-09 16:44",
  }),
];

export const seedSummary = {
  datasets: 2842,
  review: 37,
  storage: "1.82 TB",
  ingestedThisMonth: 212,
  high: 2417,
  medium: 389,
  low: 36,
};

export const seedJobs = [
  {
    id: "JOB-20240515-018",
    source: "Inbox",
    startedAt: "2024-05-15 14:28",
    finishedAt: "2024-05-15 14:33",
    status: "已完成",
    statusCode: "complete",
    detected: 18,
    verified: 18,
    committed: 15,
    note: "3 组低置信度数据已进入待审核队列",
  },
  {
    id: "JOB-20240514-017",
    source: "参考库",
    startedAt: "2024-05-14 09:10",
    finishedAt: "2024-05-14 09:17",
    status: "已完成",
    statusCode: "complete",
    detected: 42,
    verified: 42,
    committed: 42,
    note: "仅建立索引，未改动源文件",
  },
  {
    id: "JOB-20240513-016",
    source: "Inbox",
    startedAt: "2024-05-13 17:31",
    finishedAt: "—",
    status: "待审核",
    statusCode: "review",
    detected: 8,
    verified: 8,
    committed: 5,
    note: "等待确认 3 组分类建议",
  },
];

export const seedRules = [
  {
    id: "rule-sem-pair",
    name: "SEM 图像与文本旁车配对",
    description: "同目录、同文件名主体的 TIF/TIFF 与 TXT 归并为一个采集数据集。",
    scope: "SEM",
    priority: 10,
    version: "v1.4",
    enabled: true,
    source: "rule",
    matches: 238,
  },
  {
    id: "rule-tensile-bundle",
    name: "拉伸仪器原生文件包",
    description: "识别 ID_TENS、IS_TENS、RFN 及同主体文件的采集包关系。",
    scope: "TENSILE",
    priority: 20,
    version: "v1.2",
    enabled: true,
    source: "rule",
    matches: 31,
  },
  {
    id: "rule-material-recycled",
    name: "回收料路径标记",
    description: "路径包含“回收料”或 recycle 时，建议材料状态为回收料。",
    scope: "全局",
    priority: 30,
    version: "v1.1",
    enabled: true,
    source: "rule",
    matches: 96,
  },
  {
    id: "rule-reference-safe",
    name: "参考库只读保护",
    description: "data ref 下的数据仅建立索引，禁止移动、覆盖或自动改名。",
    scope: "REFERENCE",
    priority: 1,
    version: "v2.0",
    enabled: true,
    source: "rule",
    matches: 822,
  },
  {
    id: "rule-user-gpc-suffix",
    name: "GPC 特殊后缀",
    description: "Python regex：mystery\\.special$",
    pattern: "mystery\\.special$",
    label: "GPC",
    scope: "GPC",
    priority: 40,
    version: "v1",
    enabled: false,
    source: "user",
    matches: null,
  },
];

export const seedConfig = {
  referencePath: "C:\\Research Data\\data ref",
  inboxPath: "C:\\Research Data\\inbox",
  vaultPath: "C:\\Research Data\\vault",
  catalogPath: "C:\\Research Data\\catalog\\academic_vault.sqlite3",
  retainSource: true,
  verifySha256: true,
  autoScan: true,
  scanInterval: "15 分钟",
  model: "local-lightweight-v1",
  confidenceThreshold: 0.82,
};

export const filterOptions = {
  projects: ["全部项目", ...new Set(seedDatasets.map((item) => item.project))],
  materialStates: ["全部", "干燥态", "回收料", "未知"],
  modalities: ["全部", ...new Set(seedDatasets.map((item) => item.modalityLabel))],
  formats: ["全部", ...new Set(seedDatasets.map((item) => item.format))],
};
